/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ardi13790.telebot;

/**
 *
 * @author ASUS
 */
public class frmBot extends javax.swing.JFrame {

    /**
     * Creates new form frmBot
     */
    public frmBot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        mnMember = new javax.swing.JMenu();
        mnCommand = new javax.swing.JMenu();
        mnChat = new javax.swing.JMenu();
        mnBroadcast = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("BOT TELEGRAM");

        jMenu4.setText("User");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        mnMember.setText("Member");
        mnMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnMemberMouseClicked(evt);
            }
        });
        mnMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMemberActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnMember);

        mnCommand.setText("Command");
        mnCommand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnCommandMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnCommand);

        mnChat.setText("History Chat");
        mnChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnChatMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnChat);

        mnBroadcast.setText("Broadcast");
        mnBroadcast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnBroadcastMouseClicked(evt);
            }
        });
        mnBroadcast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBroadcastActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnBroadcast);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 289, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMemberActionPerformed
        // TODO add your handling code here:
        new frmMember().setVisible(true);
    }//GEN-LAST:event_mnMemberActionPerformed

    private void mnMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnMemberMouseClicked
        // TODO add your handling code here:
        new frmMember().setVisible(true);
    }//GEN-LAST:event_mnMemberMouseClicked

    private void mnChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnChatMouseClicked
        // TODO add your handling code here:
        new frmMessage().setVisible(true);
    }//GEN-LAST:event_mnChatMouseClicked

    private void mnCommandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnCommandMouseClicked
        // TODO add your handling code here:
        new frmCommand().setVisible(true);
    }//GEN-LAST:event_mnCommandMouseClicked

    private void mnBroadcastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBroadcastActionPerformed
        // TODO add your handling code here:
        new frmBroadcast().setVisible(true);
    }//GEN-LAST:event_mnBroadcastActionPerformed

    private void mnBroadcastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnBroadcastMouseClicked
        // TODO add your handling code here:
        new frmBroadcast().setVisible(true);
    }//GEN-LAST:event_mnBroadcastMouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        new frmUser().setVisible(true);
    }//GEN-LAST:event_jMenu4MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu mnBroadcast;
    private javax.swing.JMenu mnChat;
    private javax.swing.JMenu mnCommand;
    private javax.swing.JMenu mnMember;
    // End of variables declaration//GEN-END:variables
}
