/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ardi13790.telebot;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Scanner;
import java.awt.*;

/**
 *
 * @author ASUS
 */
public class frmCommand extends javax.swing.JFrame {

    /**
     * Creates new form frmMember
     */
    DefaultTableModel tabModel;
    ResultSet RsProduk=null;
    
    public frmCommand() {
        initComponents();
        tampil_data();
        set_editOff();
    }
    
    private void tampil_data(){
        try{
            Object[] judul_kolom = {"Command", "Reply", "Information"};
            tabModel=new DefaultTableModel(null,judul_kolom);
            tblCommand.setModel(tabModel);
            
            Connection conn=(Connection)KoneksiMySql.koneksiDB();
            Statement stt=conn.createStatement();
            tabModel.getDataVector().removeAllElements();
            
            RsProduk=stt.executeQuery("SELECT * from keyword");  
            while(RsProduk.next()){
                Object[] data={
                    RsProduk.getString("command"),
                    RsProduk.getString("reply"),        
                    RsProduk.getString("keterangan")        
                };
               tabModel.addRow(data);
            }                
        } catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
        // disable button
        btnSimpan.setEnabled(false);
        btnKoreksi.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(false);
        btnKeluar.setEnabled(true);
    }
    
    void tbl_keForm(){
        txtCommand.setText(tabModel.getValueAt(tblCommand.getSelectedRow(),0)+"");
        txtReply.setText(tabModel.getValueAt(tblCommand.getSelectedRow(),1)+"");
        txtInfo.setText(tabModel.getValueAt(tblCommand.getSelectedRow(),2)+"");
        
        btnKoreksi.setEnabled(true);
        btnHapus.setEnabled(true);
        btnBatal.setEnabled(true);
        btnKeluar.setEnabled(true);
        btnSimpan.setEnabled(false);
    }
    
    private void bersih_data(){
        txtCommand.setText("");
        txtReply.setText("");
        txtInfo.setText("");
    } 
    
    private void set_editOff(){
        txtCommand.setEnabled(false);
        txtReply.setEnabled(false);
        txtInfo.setEnabled(false);
    }
    
    private void set_editOn(){
        txtCommand.setEnabled(true);
        txtReply.setEnabled(true);
        txtInfo.setEnabled(true);
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCommand = new javax.swing.JTable();
        txtCommand = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnKoreksi = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtReply = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextArea();
        information = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Command");

        jLabel2.setText("Reply");

        tblCommand.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Command", "Reply", "Information"
            }
        ));
        tblCommand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCommandMouseClicked(evt);
            }
        });
        tblCommand.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tblCommandCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        tblCommand.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblCommandPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblCommand);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKoreksi.setText("Koreksi");
        btnKoreksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKoreksiActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        txtReply.setColumns(20);
        txtReply.setRows(5);
        jScrollPane2.setViewportView(txtReply);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Form Command");

        txtInfo.setColumns(20);
        txtInfo.setRows(5);
        jScrollPane3.setViewportView(txtInfo);

        information.setText("Keterangan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKoreksi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKeluar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(information)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCommand, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3))))
                        .addGap(0, 139, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCommand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(information)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnSimpan)
                    .addComponent(btnKoreksi)
                    .addComponent(btnHapus)
                    .addComponent(btnBatal)
                    .addComponent(btnKeluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        bersih_data();
        txtCommand.requestFocus();
        btnTambah.setEnabled(false);
        btnKeluar.setEnabled(false);
        btnSimpan.setEnabled(true);
        btnKoreksi.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(true);
        set_editOn();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tblCommandPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblCommandPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCommandPropertyChange

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        bersih_data();
        btnTambah.setEnabled(true);
        btnKeluar.setEnabled(true);
        btnSimpan.setEnabled(false);
        btnKoreksi.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(false);
        set_editOff();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void tblCommandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCommandMouseClicked
        // TODO add your handling code here:
        set_editOn();
        btnTambah.setEnabled(false);
        btnKeluar.setEnabled(false);
        btnSimpan.setEnabled(false);
        btnKoreksi.setEnabled(true);
        btnHapus.setEnabled(true);
        btnBatal.setEnabled(true);
        txtCommand.setEnabled(false);
        tbl_keForm();
    }//GEN-LAST:event_tblCommandMouseClicked

    private void btnKoreksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKoreksiActionPerformed
        // TODO add your handling code here:
        btnTambah.setEnabled(true);
        btnKeluar.setEnabled(true);
        btnSimpan.setEnabled(false);
        btnKoreksi.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(false);
        
        String tCommand=txtCommand.getText();
        String tReply=txtReply.getText();
        String tInfo=txtInfo.getText();
        
        if (tCommand.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"Command masih kosong!");
            txtCommand.requestFocus();
        }else if (tReply.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Reply masih kosong!");
            txtReply.requestFocus();
        }else if (tInfo.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Info masih kosong!");
            txtInfo.requestFocus();
        }else{
            try{
                Connection conn=(Connection)KoneksiMySql.koneksiDB();
                Statement stt=conn.createStatement();
                stt.executeUpdate("UPDATE keyword SET command='"+tCommand+"', reply='"+tReply+"' , keterangan='"+tInfo+"' "
                        + "WHERE command='"+tCommand+"'");
                bersih_data();
                tampil_data();
                set_editOff();
                JOptionPane.showMessageDialog(this,"Data berhasil diubah","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Ubah data gagal\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnKoreksiActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        btnTambah.setEnabled(true);
        btnKeluar.setEnabled(true);
        btnSimpan.setEnabled(false);
        btnKoreksi.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(false);
        
        String tCommand=txtCommand.getText();

        if (tCommand.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"Command tidak boleh kosong!");
            txtCommand.requestFocus();
        }else if(JOptionPane.showConfirmDialog(null,"Apakah anda yakin akan menghapus data ini?",
            "Informasi",JOptionPane.OK_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE)==JOptionPane.OK_OPTION){
            try{
                Connection conn=(Connection)KoneksiMySql.koneksiDB();
                Statement stt=conn.createStatement();
                stt.executeUpdate("DELETE FROM keyword WHERE command='"+tCommand+"'");
                bersih_data();
                tampil_data();
                set_editOff();
                JOptionPane.showMessageDialog(this,"Data berhasil dihapus","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Data gagal dihapus\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblCommandCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tblCommandCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCommandCaretPositionChanged

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String tCommand=txtCommand.getText();
        String tReply=txtReply.getText();
        String tInfo=txtInfo.getText();
        
        btnTambah.setEnabled(true);
        btnKeluar.setEnabled(true);
        btnSimpan.setEnabled(false);
        btnKoreksi.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(false);

        if (tCommand.isEmpty() ) {
            JOptionPane.showMessageDialog(null,"Command masih kosong!");
            txtCommand.requestFocus();
        }else if (tReply.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Reply masih kosong!");
            txtReply.requestFocus();
        }else if (tInfo.isEmpty()) {
            JOptionPane.showMessageDialog(null,"Info masih kosong!");
            txtInfo.requestFocus();
        }else{
            try{
                Connection conn=(Connection)KoneksiMySql.koneksiDB();
                Statement stt=conn.createStatement();
                stt.executeUpdate("INSERT INTO keyword (command, reply, keterangan)" + "VALUES('"+tCommand+"','"+tReply+"','"+tInfo+"')");
                bersih_data();
                tampil_data();
                set_editOff();
                JOptionPane.showMessageDialog(this,"Data berhasil disimpan","Success",JOptionPane.INFORMATION_MESSAGE);
            } catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Data gagal disimpan\n"+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCommand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCommand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCommand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCommand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCommand().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKoreksi;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel information;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblCommand;
    private javax.swing.JTextField txtCommand;
    private javax.swing.JTextArea txtInfo;
    private javax.swing.JTextArea txtReply;
    // End of variables declaration//GEN-END:variables
}
